### ISSUE TITLE
2.5版本会自动删除数据

### ISSUE THREAD

**Issue by icanye** [LightAPIs/Gloria-X#1]
测试了很多次，包括自动更新，定期运行js脚本，Edge（Chromium）以及Chrome都是一样的问题，会清空代码文件
后来找了个老版本的解压安装上了，数据还原回来了
Edge数据文件
AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\ndcileolkflehcjpmjnfbnaibdcgglog
Chrome数据文件
\AppData\Local\Google\Chrome\User Data\Default\Local Extension Settings\npdafhgodaenfglcfkkbnmdbfkgfadbh

**Comment by LightAPIs** [comment]
### 感谢你的反馈，同时对由于 bug 而造成使用上的困扰感到抱歉。

---

我这边已经能够复现这个问题，并计划在下一个版本中修复。
**目前有一个临时的解决办法是：先在旧版本中打开选项页面随意改动一下设置(例如切换一下外观)，之后再更新至 v2.5.0 版本就不会出现这个问题了。**

**Comment by LightAPIs** [comment]
这个问题已经在 [v2.6.0](https://github.com/LightAPIs/Gloria-X/releases/tag/v2.6.0) 中处理并修复了。
