### ISSUE TITLE
疑问+建议

### ISSUE THREAD

**Issue by DuangXT** [LightAPIs/Gloria-X#12]
【疑问】
想自定义cookie/referer，但是在request中写头信息报错了。回来插件设置中果然看到了修改请求头，于是试了下，可是测试过后并没效果。不知道是否是我的使用方式不对？
另外域名内是否填写完整域名？（比如 www.baidu.com）
还是只填写一级域名是否可以匹配到二级以上的域名？
在亦者能否使用通配符？或者表达式？

【建议】
#10 的新独立窗口的按钮确实可以考虑一下。
而我还有一个建议是希望增加在浏览器标签内打开的按钮（目前我是在通知记录内使用鼠标中键打开，不然就是把 popup.html 加到书签）；顺便能否将body内容居个中。
忘记补充一点：能否导出设置，这样就能备份自己设置过的请求头信息。如果可以的话能否将设置和任务合并在同一个文件？

**Comment by LightAPIs** [comment]
- 我这边测试了下，设置中的修改请求头的功能是正常，所以我不清楚你具体是遇到什么问题导致修改无效。至于所需要填写的域名，例如对于 `https://www.example.com/` 网址，填写 `www.example.com` 或 `example.com` 都是可以的。
- 关于 #10 上提到的按钮，之前没有加上是因为单独在窗口右上角放置一个按钮以后，界面看起来会不对称，所以就没加上；不过其实可以将原本的"添加"按钮也一并放置在左上角就可以了。
- 让窗口框架居中确实不错 👌
- 配置的请求头是可以单独导出的；设置的导入/导出后面有时间再加上吧。
- 至于任务和设置拆分的原因是：所导出的任务文件其实是可以再另外导入回 [Gloria](https://github.com/BlackGlory/Gloria) 中；另外插件在处理导入功能时是支持可选的导入部分内容，如果所有不同类型的内容混合在一起，处理起来就很混乱。

**Comment by DuangXT** [comment]
感谢解答。
- 原来导出功能是为了兼容原版的Gloria，那我理解了。
- 请求头的配置是我马虎了，没有看到底下的导入导出按钮。另外后续测试其实已经理解请求头的匹配逻辑了，只是忘记上来修改issue
- 独立窗口的按钮我的想法也是【添加】的样式，其实直接套用在右下角我也觉得合适。
- 加油

**Comment by DuangXT** [comment]
再反馈一个不痛不痒的小bug：
通知记录里面当前查看的任务记录是标记成【is-active】，然后查看过程中如果有任务执行并且更新了新的记录，li增加了，但是is-active没有跟着往下走，停在了原来的位置。
本来不痛不痒，直到我一次看完消息下意识对着黄色的任务右键清空…………
