### ISSUE TITLE
能适配一下chrome暗黑模式吗?

### ISSUE THREAD

**Issue by Noah1995** [LightAPIs/Gloria-X#2]
![image](https://user-images.githubusercontent.com/25548230/138811441-b937e4fc-8a32-43dd-9309-ebc6853fe93d.png)

**Comment by LightAPIs** [comment]
所提到的问题已经在 [v2.9.0](https://github.com/LightAPIs/Gloria-X/releases/tag/v2.9.0) 中作了改进。
