### ISSUE TITLE
开发者你好。这个插件在surface上显示的字体太小了，小到看不清……烦请调整一下，谢谢

### ISSUE THREAD

**Issue by FeiLZX3Km** [LightAPIs/Gloria-X#3]

**Comment by LightAPIs** [comment]
是指的插件的弹出窗口还是说所有的插件页面呢？

如果是插件的弹出窗口，有没有在浏览器设置中使用全局网页缩放？理论上字体大小是浏览器 100% 缩放时的大小。

**Comment by FeiLZX3Km** [comment]
> 

你好。我指的是，插件的弹出窗口，并且，也已经在反馈之前尝试过全局缩放功能了，不能奏效。

所有的插件页面上面的字体是正常的。

**Comment by LightAPIs** [comment]
因为我这边没有办法复现这个问题，试试右键点击插件图标，然后点击最底部的"审查弹出内容"，在弹出的窗口中切换至"元素(Elements)"分页，如图：

![elements](https://cdn.jsdelivr.net/gh/LightAPIs/PicGoImg@master/img/202111261910780.jpg)

看看 `<body>` 标签中的 `zoom` 是多少，正常的话它应该会和全局网页缩放比例成反比。如果没有调整过全局网页缩放比例的话应该会和图片一样值是 `100%`。

**Comment by FeiLZX3Km** [comment]
![image](https://user-images.githubusercontent.com/21981195/143575190-0a729870-08b8-472c-b229-e9a1c1cef87a.png)
默认缩放比例情况下，就是这个图片里面的内容。
放大后，还是这个图片里面的数值。

**Comment by LightAPIs** [comment]
我已经更新了新版本 [v2.11.0](https://github.com/LightAPIs/Gloria-X/releases/tag/v2.11.0) 以支持在设置中自定义弹出窗口的缩放比例，理论上这个问题在将值设定为 200% 后能恢复正常。

不过有一点尴尬的是，我注意到你是使用浏览器的是 Edge，如果该插件是在 Edge addons 中下载的话，要想等到商店中的版本更新到该版本可能需要一些时间。因为 Edge addons 的审核时间非常，至少要一周以上，并且我上一个提交到 Edge 的版本到目前为止还没有审核完成。😂

**Comment by FeiLZX3Km** [comment]
> 

为您的敬业精神而感动。
但是不得给您一个小小的提示就是……您修复了一个问题的同时，也附带创造了新的bug.
当crx文件安装后，弹出的插件页面确实挺大的。但是，若在设置页面内部进行调整，将缩放比例数值设置为100以下的任何一个数值，窗口都将再次回到以前看不清字的状态。并且，将数值调回到100亦无法恢复。解决方法就是，卸载插件并且重新安装。

**Comment by LightAPIs** [comment]
在首次安装时没有设置值，所以没有对弹出窗口自动缩放调整(一种针对调整过浏览器全局缩放级别后窗口内容溢出的修正)，看到的就是正常的窗口大小了。

但是在改动过设置以后就会应用这种自动缩放调整，我已经在上面的回复中有提及，按照你截图中的情况，这个值需要调整到至少 200% 才能修正到适合观看的大小，调整为 220% 就会和初始安装时大小。

**Comment by FeiLZX3Km** [comment]
> 

YES，调整好了。辛苦了。
