### ISSUE TITLE
能不能借鉴一下Your notifier

### ISSUE THREAD

**Issue by Noah1995** [LightAPIs/Gloria-X#4]
https://user-images.githubusercontent.com/25548230/147843461-51ccf1d4-a7b5-4d7e-9412-b6cd3d01c9f2.mp4

https://chrome.google.com/webstore/detail/your-notifier/ijkpkehidneobagkboaoapccnfnnmemg
Your notifier 可以直接右键选择元素添加还能支持Query...
能解决css找不到文字...
缺点就是没有封面和刷新1分钟太长了...

**Comment by LightAPIs** [comment]
目前没有打算增强右键选择元素功能的计划，插件本身的定位和工作核心并不在这方面。

**Comment by Noah1995** [comment]
好吧...
那有些网站找不到文字不会增强了吗?

1丶还有一个小功能
那个图标如果没有设置可选
能否拓展自动添加favicon api或者点击创建输入框做成选择选项自动完成
http://favicon.yandex.net/favicon/网址
https://api.iowen.cn/favicon/get.php?url=网址

**Comment by LightAPIs** [comment]
> 好吧……那个人网站找不到文字不会增强？
> 
> 1 还有一个小功能 那个图标如果没有设置可选 可以自动添加图标 api 或者点击创建输入框生成选择选项自动完成 [http://favicon.yandex.net/favicon/网址](http://favicon.yandex.net/favicon/%E7%BD%91%E5%9D%80) [https://api .iowen.cn/favicon/get.php?url=网址](https://api.iowen.cn/favicon/get.php?url=%E7%BD%91%E5%9D%80)

因为插件其实本身是依赖用户具有一定的 javascript 编写能力，如果不会编写，那只能试试通过浏览器的开发者工具定位到元素以后右键 `Copy` → `Copy selector` 了。

如果不想手动输入图标地址，可以勾选`选项` → `常规设置` → `通知` → `允许自动检测并获取网站图标`。

**Comment by Noah1995** [comment]
允许自动检测并获取网站图标
我勾选了的但是没用啊...

**Comment by LightAPIs** [comment]
> 允许自动检测并获取网站图标 我勾选了的但是没用啊...

如果是你一楼视频里的网站，我这边测试了一下，是可以自动检测到网站图标的呀。开启设置以后 `iconUrl` 留空就行了。

**Comment by Noah1995** [comment]
一楼那个确实可以...
我用百度贴吧和虎扑就不行...

**Comment by LightAPIs** [comment]
> 一楼那个确实可以... 我用百度贴吧和虎扑就不行...
> 
> 那个文字没法找到好像是这个 无法为所选网页元素自动生成观察任务，有可能因为它是基于 Ajax 等技术动态加载而来。
> 
> 贴吧搜索界面用f12找到的标题元素填入会乱码怎么办 https://tieba.baidu.com/f/search/res?ie=utf-8&qw= 你随便填文字搜索看一下 ![Snipaste_2022-01-03_05-13-07](https://user-images.githubusercontent.com/25548230/147889639-ca9f3fd9-c909-4e31-90ca-e2dd36ed7139.png)

因为自动检测图标其实就是按照当前域名查找一些网站会通用的图标存放位置，但是如果网站本身使用了一些独特的路径存放图标时就无法自动查找到了，例如所提到的虎扑网站 Logo 地址是：`https://w1.hoopchina.com.cn/images/pc/old/favicon.ico`。

---

结果会出现乱码一般是因为网站使用了 `utf-8` 以外的编码，比如你截图中的网站采用了 `GBK` 的编码，相关的解决方法可以参考：https://github.com/BlackGlory/Gloria/tree/master/docs#常见问题

例如：
```javascript
// 原来的任务代码
const html = await fetch("https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=1&rn=10&un=&only_thread=0&sm=1&sd=&ed&pn=2").then(res => res.text());
const $ = cheerio.load(html);
// ...

// 修改成这样
const html = await fetch("https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=1&rn=10&un=&only_thread=0&sm=1&sd=&ed&pn=2").then(res => res.arrayBuffer()).then(buf => new TextDecoder('gbk').decode(buf));
const $ = cheerio.load(html);
// ...
```
