### ISSUE TITLE
请教语法问题下

### ISSUE THREAD

**Issue by dnknn** [LightAPIs/Gloria-X#7]
```js
Promise.all([importScripts('gloria-utils'), fetch(`https://www.ithome.com/`).then(res => res.arrayBuffer())]).then(([{ cheerio }, html]) =>	{
		html = new TextDecoder('utf-8').decode(html)
		let $ = cheerio.load(html)
////////////在这里⥅请教3个问题👇
	return $(`li.n a`).map(ee=>	{return	{message: 1111, url: 9999}  } )
////////////在这里⥅请教3个问题👆
	.get()
}).then(commit)
```
-------------------------

> 上面遍历 `document.querySelectorAll('li.n a')` 元素选择器,有效, 但请问下:

- 1️⃣ .
```js
	return [1,2].map(ee=> {return {message: 1111, url: 9999}  } )  //❌为什么就无效了?
```

- 2️⃣  如何不用`.map`遍历, 而获得 `{message: 1111, url: 9999}` ?
   > 有时,我们不需要遍历推送, 而是只需一个通知推送就够了, 此时就不应该用**遍历**
```js
if($(`li.n a`)[0])	return	{message: 1111, url: 9999}   //❌为什么就无效了?
if($(`li.n a`)[0])	return	[ {message: 1111, url: 9999} ]  //❌为什么就无效了?
```

- 3️⃣ 如何改写为 **原生`JavaScript`语法** 呢? _因为不懂 jq 语法_
```html
<a href="/abc.html" title=标题tooltip标题 >链接文本</a>
```
- ❌无效👇 　`location.origin`、`.getAttribute()` 这些统统失效了
```js
return $(`li.n a`).map(每项=>	{
   return	{
     message: 每项.title,  // 等价👉  每项.getAttribute`title`
     url: location.origin + 每项.getAttribute`href`   }  
})
```

- ❌无效👇
```js
return $(`li.n a`).map(每项=>	{
   return	{
     message: 每项.title,
     url: 每项.href,   // 原生js能自动获取完整的 URL 但这里不行
   }  
})
```

- 4️⃣ 如何使用 原生js选择器语法? 例如 `document.querySelectorAll()`
   ❌无效👇 
```js
return document.querySelectorAll`li.n a`.map(每项=>	{
   return	{
     message: 每项.parentNode.title,
     url: 每项.href,
   }  
})
```
- 5️⃣ 或者换句话说, 可以使用`fetch()`对象URL里的 `document`/`window`对象吗?

**Comment by LightAPIs** [comment]
# 1

若仅仅单纯是 `return [1,2].map(ee=> {return {message: 1111, url: 9999}  } )` 这一行应该应该有效的呀，实际测试也正常的；还是说你*不小心*还连接了一个 `.get()` 方法，例如：

```js
return [1,2].map(ee=> {return {message: 1111, url: 9999}  } )
  .get()
```

如果是这样那将会引发 `TypeError`，因为 `Array.prototype.map()` 返回一个新数组(`Array`)，但是**并不存在 `Array.prototype.get()` 这样的方法**！

# 2

这两行发上去没发现有什么问题，实际各自单独运行测试了下也没有报错，你是具体遇到了什么问题？

另外从你所描述想要实现的效果上来看，这样写会更好些：

```js
if($(`li.n a`).length > 0)	return	{message: 1111, url: 9999}
// or
if($(`li.n a`).length > 0)	return	[ {message: 1111, url: 9999} ]
```

# 3

## 关于 `location.origin`

你可以在脚本中读取 `location.origin`，但脚本代码是在由插件发起的 [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) 线程中运行，所以 `location.origin` 的结果应当会是 `chrome-extension://{id}`；另外严格来说 `location` 属性是在 `window` 上的，所以即便脚本代码不是在 Worker 中运行，也无法通过 `location.origin` 这种形式来获取到 `fetch()` 中 URL 的 `origin` 值。

## 关于 `$('li.n a').map()`

`cheerio.Cheerio.map()` 中的回调函数接收两个参数，依次是索引值和 `cheerio.Element` 对象。**这与 `Array.prototype.map()` 中的回调函数所接收的参数不相同**。所以想实现类似的效果大概需要这样写：

```js
return $('li.n a')
    .map((_index, item) => {
      const ele = $(item);
      return {
        message: ele.attr('title'),
        url: ele.attr('href'),
      };
    })
    .get();
```

# 4&5

Worker 线程上下文中不存在 `document` 对象，所以无法使用类似 `document.querySelectorAll()` 这样的方法。

**Comment by dnknn** [comment]
十分感谢作者的仔细答复💯!
因为只能Web页面DOM对象原生JavaScript, 所以代码示例都是来自于其它人写的.

- 现在明白了, `.get()` 只能衔接于 `cheerio.Cheerio.map()`, 其它原生对象链接 `.get()` 就无效了.

- `Array.prototype.map((每项, 索引)=>...)` ⚔ `cheerio.Cheerio.map((索引, 每项)=>...)` 的回调参数确实反着来的

- 现在懂了, 无法使用 `document`/`window` 这些对象, 故也不能用 `.querySelector()` js选择器

-------------

- 最后请问下 `$('li.n a')` 这里的 `$` 不是 jq语法里的那个 `$` 吧??
- 这里 `$` 的原理, 是不是 `fetch`请求URL解析html后, 插件内部有个已定义的虚拟DOM对象, 然后 `$` 指向它, 再引入jq语法库使用jq语法来操作这个虚拟DOM对象

**Comment by LightAPIs** [comment]
1. `$` 只是一个约定俗成的标识符变量名，你其实可以使用任意合法的变量名称，此处的 `$` 一般是指 `cheerio.load()` 方法返回的 `Cheerio` 对象，本质上它和 jQuery 中的 `$` 标识符不一样，cheerio 也只是实现了 jQuery 的一个子集而已。
2. 也可以这么理解吧。cheerio 提供能解析 HTML/XML 标记的 API，并通过解析方法返回的 `Cheerio` 对象来遍历或操作 DOM。*但注意解析标记后所返回的并不是一个虚拟 DOM 对象，而是一个 `Cheerio` 对象，它支持一些类 jQuery 的方法。*

**Comment by LightAPIs** [comment]
> * 那请教能使用 [`DOMParser()`](https://developer.mozilla.org/zh-CN/docs/Web/API/DOMParser)⤤　　这个原生的 API 吗?

这是原生的 DOM API，并且可以在浏览器上下文环境中使用，但很遗憾，它并没有在 Workers 等环境中实现。基本上目前 DOM APIs 都没有在 Workers 中被实现(*这不是一个简单的事情*)，一些相关的讨论你可以见：whatwg/dom#1217
